#!/bin/sh

set -e

cd /app

VUE_APP_AUTH_URL=${VUE_APP_AUTH_URL:-}
VUE_APP_AUTH_CLIENT=${VUE_APP_AUTH_CLIENT:-myclient}
VUE_APP_AUTH_SCOPES=${VUE_APP_AUTH_SCOPES:-}
HTTPS=${HTTPS:-false}
HTTPS_KEY=${HTTPS_KEY:-}
HTTPS_CERT=${HTTPS_CERT:-}
HTTPS_CA=${HTTPS_CA:-}
PUBLIC_URL=${PUBLIC_URL:-http://localhost:9090}
ALLOWED_HOSTS=${ALLOWED_HOSTS:-.local}

echo "VUE_APP_AUTH_URL=$VUE_APP_AUTH_URL
VUE_APP_AUTH_CLIENT=$VUE_APP_AUTH_CLIENT
VUE_APP_AUTH_SCOPES=$VUE_APP_AUTH_SCOPES
HTTPS=$HTTPS
HTTPS_KEY=$HTTPS_KEY
HTTPS_CERT=$HTTPS_CERT
HTTPS_CA=$HTTPS_CA
PUBLIC_URL=$PUBLIC_URL
ALLOWED_HOSTS=$ALLOWED_HOSTS
" > .env

#cat .env

export -n VUE_APP_AUTH_URL
export -n VUE_APP_AUTH_CLIENT
export -n VUE_APP_AUTH_SCOPES
export -n HTTPS
export -n HTTPS_KEY
export -n HTTPS_CERT
export -n HTTPS_CA
export -n PUBLIC_URL
export -n ALLOWED_HOSTS

set PATH=/app/node_modules/.bin:$PATH

npm run serve
